-- 게시글 테이블에 메뉴 ID 컬럼 추가
ALTER TABLE BBS_ARTICLE
ADD COLUMN MENU_ID INT UNSIGNED NOT NULL COMMENT 'FK: 메뉴 ID' AFTER BBS_ID,
ADD CONSTRAINT fk_bbs_article_menu FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID) ON DELETE CASCADE;

-- 기존 게시글의 메뉴 ID 업데이트 (게시판과 연결된 메뉴 ID로 설정)
UPDATE BBS_ARTICLE a
JOIN MENU m ON m.TARGET_ID = a.BBS_ID AND m.TARGET_TYPE = 'BBS'
SET a.MENU_ID = m.MENU_ID
WHERE a.MENU_ID IS NULL; 