-- 게시글 첨부파일
CREATE TABLE BBS_ATTACHMENT (
  ATTACHMENT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 첨부파일 ID',
  NTT_ID INT UNSIGNED NOT NULL COMMENT 'FK: 게시글 ID',
  ORIGIN_NAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
  SAVED_NAME VARCHAR(255) NOT NULL COMMENT '저장 파일명',
  MIME_TYPE VARCHAR(100) NOT NULL COMMENT 'MIME 타입',
  SIZE BIGINT NOT NULL COMMENT '파일 크기(bytes)',
  EXT VARCHAR(20) NOT NULL COMMENT '파일 확장자',
  FILE_ORDER INT DEFAULT 0 COMMENT '파일 순서',
  CREATED_BY VARCHAR(36) NULL COMMENT '생성자 ID',
  CREATED_IP VARCHAR(45) NULL COMMENT '생성자 IP',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  UPDATED_BY VARCHAR(36) NULL COMMENT '수정자 ID',
  UPDATED_IP VARCHAR(45) NULL COMMENT '수정자 IP',
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
  CONSTRAINT fk_bbs_attachment_article FOREIGN KEY (NTT_ID) REFERENCES BBS_ARTICLE(NTT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시글 첨부파일'; 

ALTER TABLE bbs_article
ADD COLUMN has_image_in_content BOOLEAN DEFAULT FALSE COMMENT '본문 내 이미지 포함 여부';