CREATE TABLE `user` (
  `uuid` varchar(36) NOT NULL,
  `username` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(20) NOT NULL,
  `avatar_url` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `created_by` varchar(36) DEFAULT NULL,
  `created_ip` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_by` varchar(36) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_ip` varchar(45) DEFAULT NULL,
  `organization_id` varchar(36) NOT NULL COMMENT '조직 ID',
  `group_id` varchar(36) NOT NULL COMMENT '그룹 ID',
  `reset_token` varchar(255) DEFAULT NULL COMMENT '비밀번호 재설정 토큰',
  `reset_token_expiry` timestamp NULL DEFAULT NULL COMMENT '비밀번호 재설정 토큰 만료 시간',
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `user` (`uuid`),
  CONSTRAINT `user_ibfk_2` FOREIGN KEY (`updated_by`) REFERENCES `user` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 