-- 1. 게시판 마스터 테이블
CREATE TABLE BBS_MASTER (
    BBS_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 게시판 ID',
    BBS_NAME VARCHAR(100) NOT NULL COMMENT '게시판 이름',
    SKIN_TYPE ENUM('BASIC','FAQ','QNA','PRESS','FORM') NOT NULL COMMENT '게시판 스킨 유형',
    READ_AUTH VARCHAR(50) DEFAULT 'PUBLIC' COMMENT '읽기 권한 코드',
    WRITE_AUTH VARCHAR(50) DEFAULT 'STAFF' COMMENT '쓰기 권한 코드',
    ADMIN_AUTH VARCHAR(50) DEFAULT 'ADMIN' COMMENT '관리 권한 코드',
    DISPLAY_YN TINYINT(1) DEFAULT 1 COMMENT '노출 여부(1=YES)',
    SORT_ORDER INT DEFAULT 0 COMMENT '게시판 정렬 순서',
    ATTACHMENT_LIMIT INT DEFAULT 0 COMMENT '첨부파일 최대 개수',
    ATTACHMENT_SIZE INT DEFAULT 0 COMMENT '첨부파일 최대 용량(MB)',
    EXTRA_SCHEMA JSON NULL COMMENT '추가 필드 정의(JSON Schema)',
    CREATED_BY VARCHAR(36) NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) NULL COMMENT '생성자 IP',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) NULL COMMENT '수정자 IP',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    INDEX IDX_BBS_SORT (SORT_ORDER, DISPLAY_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판 설정';

-- 2. 게시판 카테고리 테이블
CREATE TABLE BBS_CATEGORY (
    CATEGORY_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 카테고리 ID',
    BBS_ID BIGINT UNSIGNED NOT NULL COMMENT 'FK: 게시판 ID',
    CODE VARCHAR(50) NOT NULL COMMENT '카테고리 코드',
    NAME VARCHAR(100) NOT NULL COMMENT '카테고리 이름',
    SORT_ORDER INT DEFAULT 0 COMMENT '카테고리 정렬 순서',
    DISPLAY_YN TINYINT(1) DEFAULT 1 COMMENT '노출 여부(1=YES)',
    CREATED_BY VARCHAR(36) NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) NULL COMMENT '생성자 IP',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) NULL COMMENT '수정자 IP',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    FOREIGN KEY (BBS_ID) REFERENCES BBS_MASTER(BBS_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_BBS_CATEGORY_CODE (BBS_ID, CODE),
    INDEX IDX_CATEGORY_SORT (BBS_ID, SORT_ORDER, DISPLAY_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판별 카테고리';

-- 3. 게시글 테이블
CREATE TABLE BBS_ARTICLE (
    NTT_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 게시글 ID',
    BBS_ID BIGINT UNSIGNED NOT NULL COMMENT 'FK: 게시판 ID',
    PARENT_NTT_ID BIGINT UNSIGNED NULL COMMENT '부모 글 ID(답변형)',
    THREAD_DEPTH INT UNSIGNED DEFAULT 0 COMMENT '답변 깊이',
    WRITER VARCHAR(50) NOT NULL COMMENT '작성자',
    TITLE VARCHAR(255) NOT NULL COMMENT '제목',
    content MEDIUMTEXT COMMENT '내용(HTML)',
    NOTICE_YN TINYINT(1) DEFAULT 0 COMMENT '공지 여부',
    PUBLISH_START_DT DATETIME NULL COMMENT '게시 시작일',
    PUBLISH_END_DT DATETIME NULL COMMENT '게시 종료일',
    EXTERNAL_LINK VARCHAR(255) COMMENT '외부 링크 URL',
    HITS INT DEFAULT 0 COMMENT '조회수',
    DELETED_YN TINYINT(1) DEFAULT 0 COMMENT '삭제 여부(소프트 딜리트)',
    CREATED_BY VARCHAR(36) NULL COMMENT '작성자 ID',
    CREATED_IP VARCHAR(45) NULL COMMENT '작성자 IP',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성 시각',
    UPDATED_BY VARCHAR(36) NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) NULL COMMENT '수정자 IP',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    FOREIGN KEY (BBS_ID) REFERENCES BBS_MASTER(BBS_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_NTT_ID) REFERENCES BBS_ARTICLE(NTT_ID) ON DELETE SET NULL,
    INDEX IDX_ARTICLE_BBS (BBS_ID, CREATED_AT),
    INDEX IDX_ARTICLE_PARENT (PARENT_NTT_ID),
    INDEX IDX_ARTICLE_NOTICE (BBS_ID, NOTICE_YN, CREATED_AT),
    INDEX IDX_ARTICLE_SEARCH (BBS_ID, TITLE, content(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판 게시글';

-- 4. 게시글-카테고리 매핑 테이블
CREATE TABLE BBS_ARTICLE_CATEGORY (
    NTT_ID BIGINT UNSIGNED NOT NULL COMMENT 'FK: 게시글 ID',
    CATEGORY_ID BIGINT UNSIGNED NOT NULL COMMENT 'FK: 카테고리 ID',
    PRIMARY KEY (NTT_ID, CATEGORY_ID),
    FOREIGN KEY (NTT_ID) REFERENCES BBS_ARTICLE(NTT_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES BBS_CATEGORY(CATEGORY_ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE_CATEGORY (CATEGORY_ID, NTT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시글-카테고리 매핑';

