ALTER TABLE template RENAME COLUMN role TO type;

-- Template 테이블 생성
CREATE TABLE TEMPLATE (
    TEMPLATE_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '템플릿 고유 식별자',
    TEMPLATE_NM VARCHAR(100) NOT NULL COMMENT '템플릿 이름',
    TYPE ENUM('MAIN','SUB','NORMAL') NOT NULL DEFAULT 'NORMAL' COMMENT '템플릿 역할 (MAIN/SUB/NORMAL)',
    IS_PUBLISHED TINYINT(1) NOT NULL DEFAULT 0 COMMENT '게시 여부',
    VERSION_NO INT NOT NULL DEFAULT 1 COMMENT '버전 번호',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '템플릿 기본 정보 테이블';

-- Template Row 테이블 생성
CREATE TABLE TEMPLATE_ROW (
    ROW_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '행 고유 식별자',
    TEMPLATE_ID BIGINT NOT NULL COMMENT '참조하는 템플릿 ID',
    ORDINAL INT NOT NULL COMMENT '행 순서',
    HEIGHT_PX INT COMMENT '행 높이(픽셀)',
    BG_COLOR VARCHAR(20) COMMENT '배경색',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '템플릿 행 정보 테이블';

-- Template Cell 테이블 생성
CREATE TABLE TEMPLATE_CELL (
    CELL_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '셀 고유 식별자',
    ROW_ID BIGINT NOT NULL COMMENT '참조하는 행 ID',
    ORDINAL INT NOT NULL COMMENT '셀 순서',
    SPAN_JSON JSON NOT NULL COMMENT '반응형 너비 설정 (base/md/lg/xl)',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    FOREIGN KEY (ROW_ID) REFERENCES TEMPLATE_ROW(ROW_ID) ON DELETE CASCADE,
    CONSTRAINT UK_CELL_ORD UNIQUE (ROW_ID, ORDINAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '템플릿 셀 정보 테이블';

-- Template Version 테이블 생성
CREATE TABLE TEMPLATE_VERSION (
    VERSION_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '버전 고유 식별자',
    TEMPLATE_ID BIGINT NOT NULL COMMENT '참조하는 템플릿 ID',
    VERSION_NO INT NOT NULL COMMENT '버전 번호',
    LAYOUT_JSON JSON NOT NULL COMMENT '해당 버전의 레이아웃 JSON 데이터',
    UPDATER VARCHAR(50) NOT NULL COMMENT '수정자',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE(TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '템플릿 버전 관리 테이블';

-- Content 테이블 생성
CREATE TABLE CONTENT (
    CONTENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컨텐츠 고유 식별자',
    TITLE VARCHAR(255) NOT NULL COMMENT '컨텐츠 제목',
    DESCRIPTION TEXT COMMENT '컨텐츠 설명',
    CONTENT TEXT NOT NULL COMMENT '컨텐츠 본문',
    TEMPLATE_ID BIGINT NOT NULL COMMENT '사용된 템플릿 ID',
    STATUS VARCHAR(20) NOT NULL COMMENT '컨텐츠 상태 (DRAFT, PUBLISHED, EXPIRED, DELETED)',
    CREATOR_ID BIGINT NOT NULL COMMENT '생성자 ID',
    UPDATER_ID BIGINT COMMENT '수정자 ID',
    PUBLISHED_AT TIMESTAMP COMMENT '게시 일시',
    EXPIRED_AT TIMESTAMP COMMENT '만료 일시',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '삭제 여부',
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE(TEMPLATE_ID),
    FOREIGN KEY (CREATOR_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (UPDATER_ID) REFERENCES USER(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '컨텐츠 정보 테이블';

-- Template 관련 인덱스
CREATE INDEX IDX_TEMPLATE_ROLE ON TEMPLATE(TYPE) COMMENT '템플릿 역할 검색용 인덱스';
CREATE INDEX IDX_TEMPLATE_PUBLISHED ON TEMPLATE(IS_PUBLISHED) COMMENT '게시 상태 검색용 인덱스';
CREATE INDEX IDX_TEMPLATE_VERSION_TEMPLATE ON TEMPLATE_VERSION(TEMPLATE_ID) COMMENT '템플릿별 버전 조회용 인덱스';
CREATE INDEX IDX_TEMPLATE_ROW_TEMPLATE ON TEMPLATE_ROW(TEMPLATE_ID) COMMENT '템플릿별 행 조회용 인덱스';
CREATE INDEX IDX_TEMPLATE_CELL_ROW ON TEMPLATE_CELL(ROW_ID) COMMENT '행별 셀 조회용 인덱스';

-- Content 관련 인덱스
CREATE INDEX IDX_CONTENT_TEMPLATE ON CONTENT(TEMPLATE_ID) COMMENT '템플릿별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_CREATOR ON CONTENT(CREATOR_ID) COMMENT '생성자별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_UPDATER ON CONTENT(UPDATER_ID) COMMENT '수정자별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_STATUS ON CONTENT(STATUS) COMMENT '상태별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_CREATED_AT ON CONTENT(CREATED_AT) COMMENT '생성일자별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_PUBLISHED_AT ON CONTENT(PUBLISHED_AT) COMMENT '게시일자별 컨텐츠 조회용 인덱스';
CREATE INDEX IDX_CONTENT_EXPIRED_AT ON CONTENT(EXPIRED_AT) COMMENT '만료일자별 컨텐츠 조회용 인덱스';

-- 템플릿 타입 테이블 생성
CREATE TABLE TEMPLATE_TYPE (
    CODE VARCHAR(20) PRIMARY KEY COMMENT '템플릿 타입 코드',
    NAME VARCHAR(50) NOT NULL COMMENT '템플릿 타입 이름',
    DESCRIPTION VARCHAR(200) COMMENT '템플릿 타입 설명',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '템플릿 타입 코드 테이블';

-- 기본 템플릿 타입 데이터 삽입
INSERT INTO TEMPLATE_TYPE (CODE, NAME, DESCRIPTION) VALUES 
('MAIN', '메인 템플릿', '사이트의 메인 페이지에 사용되는 템플릿'),
('SUB', '서브 템플릿', '서브 페이지에 사용되는 템플릿'),
('NORMAL', '일반 템플릿', '일반 페이지에 사용되는 템플릿');

-- 기본 메인 템플릿 생성
INSERT INTO TEMPLATE (
    TEMPLATE_NM,
    TYPE,
    IS_PUBLISHED,
    VERSION_NO
) VALUES (
    '기본 메인 템플릿',
    'MAIN',
    1,
    1
);

-- 기본 서브 템플릿 생성
INSERT INTO TEMPLATE (
    TEMPLATE_NM,
    TYPE,
    IS_PUBLISHED,
    VERSION_NO
) VALUES (
    '기본 서브 템플릿',
    'SUB',
    1,
    1
);