-- Add columns to TEMPLATE table
ALTER TABLE TEMPLATE 
    -- ADD COLUMN DELETED_YN BOOLEAN NOT NULL DEFAULT FALSE COMMENT '삭제 여부',
    -- ADD COLUMN DESCRIPTION VARCHAR(500) COMMENT '템플릿 설명',
    ADD COLUMN LAYOUT_JSON JSON NOT NULL COMMENT '레이아웃 JSON 데이터'; 