-- 게시판 마스터 테이블 생성
CREATE TABLE BBS_MASTER (
  BBS_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 게시판 ID',
  BBS_NAME VARCHAR(100) NOT NULL COMMENT '게시판 이름',
  SKIN_TYPE ENUM('BASIC','FAQ','QNA','PRESS','FORM') NOT NULL COMMENT '게시판 스킨 유형',
  READ_AUTH VARCHAR(50) NOT NULL COMMENT '읽기 권한 코드',
  WRITE_AUTH VARCHAR(50) NOT NULL COMMENT '쓰기 권한 코드',
  ADMIN_AUTH VARCHAR(50) NOT NULL COMMENT '관리 권한 코드',
  DISPLAY_YN VARCHAR(1) DEFAULT 'Y' COMMENT '노출 여부',
  SORT_ORDER VARCHAR(1) DEFAULT 'D' COMMENT '게시판 정렬 순서(A=오름차순,D=내림차순)',
  NOTICE_YN VARCHAR(1) DEFAULT 'N' COMMENT '공지 여부(Y=공지,N=미공지)',
  PUBLISH_YN VARCHAR(1) DEFAULT 'N' COMMENT '게시 여부(Y=게시,N=미게시)',
  ATTACHMENT_YN VARCHAR(1) DEFAULT 'N' COMMENT '첨부파일 기능 사용여부',
  ATTACHMENT_LIMIT INT DEFAULT 0 COMMENT '첨부파일 최대 개수',
  ATTACHMENT_SIZE INT DEFAULT 0 COMMENT '첨부파일 최대 용량(MB)',
  CREATED_BY       VARCHAR(36)  NULL COMMENT '생성자 ID',
  CREATED_IP       VARCHAR(45)  NULL COMMENT '생성자 IP',
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  UPDATED_BY       VARCHAR(36)  NULL COMMENT '수정자 ID',
  UPDATED_IP       VARCHAR(45)  NULL COMMENT '수정자 IP',
  UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판 설정';

-- 카테고리 (게시판별 분류)
CREATE TABLE BBS_CATEGORY (
  CATEGORY_ID int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK: 카테고리 ID',
  BBS_ID int(20) unsigned NOT NULL COMMENT 'FK: 게시판 ID',
  CODE varchar(50) NOT NULL COMMENT '카테고리 코드',
  NAME varchar(100) NOT NULL COMMENT '카테고리 이름',
  SORT_ORDER int(11) DEFAULT 0 COMMENT '카테고리 정렬 순서',
  DISPLAY_YN varchar(1) DEFAULT 'Y' COMMENT '노출 여부(Y,N)',
  CREATED_BY VARCHAR(36)  NULL COMMENT '생성자 ID',
  CREATED_IP VARCHAR(45)  NULL COMMENT '생성자 IP',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  UPDATED_BY VARCHAR(36)  NULL COMMENT '수정자 ID',
  UPDATED_IP VARCHAR(45)  NULL COMMENT '수정자 IP',
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각'
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE KEY `UK_BBS_CATEGORY_CODE` (`BBS_ID`,`CODE`),
  KEY `IDX_CATEGORY_SORT` (`BBS_ID`,`SORT_ORDER`,`DISPLAY_YN`),
  CONSTRAINT `bbs_category_ibfk_1` FOREIGN KEY (`BBS_ID`) REFERENCES `bbs_master` (`BBS_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='게시판별 카테고리';