-- 게시글
CREATE TABLE BBS_ARTICLE (
  NTT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'PK: 게시글 ID',
  BBS_ID INT UNSIGNED NOT NULL COMMENT 'FK: 게시판 ID',
  MENU_ID INT(11) NOT NULL COMMENT 'FK: 메뉴 ID',
  PARENT_NTT_ID INT UNSIGNED NULL COMMENT '부모 글 ID(답변형)',
  THREAD_DEPTH INT UNSIGNED DEFAULT 0 COMMENT '답변 깊이',
  WRITER VARCHAR(50) NOT NULL COMMENT '작성자',
  TITLE VARCHAR(255) NOT NULL COMMENT '제목',
  content MEDIUMTEXT COMMENT '내용(HTML)',
  NOTICE_STATE VARCHAR(1) DEFAULT 'N' COMMENT '공지 여부(Y=공지,N=미공지,P=영구공지)',
  NOTICE_START_DT DATETIME DEFAULT CURRENT_DATE COMMENT '공지 시작일',
  NOTICE_END_DT DATETIME DEFAULT (CURRENT_DATE + INTERVAL 1 DAY) COMMENT '공지 종료일',
  PUBLISH_STATE VARCHAR(1) DEFAULT 'N' COMMENT '게시 여부(Y=게시,N=미게시,P=영구게시)',
  PUBLISH_START_DT DATETIME DEFAULT CURRENT_DATE COMMENT '게시 시작일',
  PUBLISH_END_DT DATETIME DEFAULT (CURRENT_DATE + INTERVAL 1 DAY) COMMENT '게시 종료일',
  EXTERNAL_LINK VARCHAR(255) COMMENT '외부 링크 URL',
  HITS INT DEFAULT 0 COMMENT '조회수',
  CREATED_BY VARCHAR(36)  NULL COMMENT '생성자 ID',
  CREATED_IP VARCHAR(45)  NULL COMMENT '생성자 IP',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  UPDATED_BY VARCHAR(36)  NULL COMMENT '수정자 ID',
  UPDATED_IP VARCHAR(45)  NULL COMMENT '수정자 IP',
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
  FOREIGN KEY (BBS_ID) REFERENCES BBS_MASTER(BBS_ID) ON DELETE CASCADE COMMENT '게시판 참조',
  FOREIGN KEY (MENU_ID) REFERENCES MENU(id) ON DELETE CASCADE COMMENT '메뉴 참조',
  FOREIGN KEY (PARENT_NTT_ID) REFERENCES BBS_ARTICLE(NTT_ID) ON DELETE SET NULL COMMENT '부모 글 참조'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판 게시글';

-- 게시글-카테고리 매핑 (M:N)
CREATE TABLE BBS_ARTICLE_CATEGORY (
  `NTT_ID` int(20) unsigned NOT NULL COMMENT 'FK: 게시글 ID',
  `CATEGORY_ID` int(20) unsigned NOT NULL COMMENT 'FK: 카테고리 ID',
  PRIMARY KEY (`NTT_ID`,`CATEGORY_ID`),
  KEY `IDX_ARTICLE_CATEGORY` (`CATEGORY_ID`,`NTT_ID`),
  CONSTRAINT `bbs_article_category_ibfk_1` FOREIGN KEY (`NTT_ID`) REFERENCES `bbs_article` (`NTT_ID`) ON DELETE CASCADE,
  CONSTRAINT `bbs_article_category_ibfk_2` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `bbs_category` (`CATEGORY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시글-카테고리 
매핑';

-- 게시글 검색을 위한 인덱스 생성
CREATE INDEX idx_article_search ON cms_bbs_article(title, content(255)); 